version: '2'
services:
  db:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: nanatomaru
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - data:/var/lib/mysql
  app:
    build: .
    links:
      - db
    tty: true
volumes:
  data: